# Generated by Django 5.0.3 on 2024-10-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_job_viewed_remove_jobapplication_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='viewed',
        ),
        migrations.AddField(
            model_name='job',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=50),
        ),
    ]
