# Generated by Django 5.0.3 on 2024-11-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_jobview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='viewed',
        ),
    ]
