# Generated by Django 5.0.3 on 2024-11-25 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_remove_job_viewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
