# Generated by Django 5.0.3 on 2024-11-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
