# Generated by Django 5.0.3 on 2024-10-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_experience_customuser_highest_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
