# Generated by Django 5.0.3 on 2024-10-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_job_viewed_jobview'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='JobView',
        ),
    ]
